### ISSUE TITLE
[HELP] TooManyRequestsException when pushing to a group chat

### ISSUE THREAD

**Issue by slux83** [line/line-bot-sdk-java#426] opened 2019-12-09 14:38 UTC
Hi,

I get the following exception on my bot when I try to push a message to a group chat:
```
com.linecorp.bot.client.exception.TooManyRequestsException: You have reached your monthly limit. :
ErrorResponse(requestId=0c34a491-e2df-4d87-8440-a89f8ae2a7e3, message=You have reached your monthly limit., details=[])
```

I can't find anywhere the right amount limit for my account. Also I'd like to extend it if possible but nowhere in my account I can see the plan settings.

Thanks for the help

**Comment by kazuki-ma** [comment] 2019-12-09 14:54
@slux83 thank you for contacting us.

As you know, the message `You have reached your monthly limit.` means your paiment plan or limit is not enough.

Could you check plan from https://manager.line.biz ?

After open your bot, please click `Settings > Activity and billing > Monthly plan`.

![1575903147842](https://user-images.githubusercontent.com/1370068/70445568-1163be00-1adf-11ea-8489-1b68c6c62b5e.jpg)

Thank you.

**Comment by slux83** [comment] 2019-12-09 15:03
Many thanks for your quick answer.
When I click change plan (as I'm on a free one) I receive a nice

```
403 Forbidden
You don't have permission to access this page.
```
![image](https://user-images.githubusercontent.com/11455148/70446337-39cac880-1a9d-11ea-9bab-59af1aa50f20.png)

And this is what I see
![image](https://user-images.githubusercontent.com/11455148/70446440-62eb5900-1a9d-11ea-8a1d-6886564db945.png)

**Comment by kazuki-ma** [comment] 2019-12-09 15:04
Thank you for your reporting. Let me check.

**Comment by kazuki-ma** [comment] 2019-12-09 15:39
Sorry I have no idea about your issue.
If you are OK, could you tell me what's the country of your account?

Looks like the issue relates the country of your bot.

(I'll check the issue tomorrow.)

**Comment by slux83** [comment] 2019-12-09 15:44
Sure, the bot is hosted on a server in Germany (EU). Same as my account. I'm not sure if this is something you can configure actually. If you tell me where to look for, I can attach a screenshot. The ID of the bot is 
```
Basic ID @edb0147w
Premium ID   @fridaybot
```

**Comment by kazuki-ma** [comment] 2019-12-10 01:52
@slux83 I confirmed.

* I'm sorry but purchase (changing plan) is not available for EU account due to our payment flow do not ready for GDPR's requirements.
* The 403 pages you saw are missing specifications and will be fixed.

**Comment by slux83** [comment] 2019-12-10 08:09
Ok thanks for the info. The issue is that my bot has to send some push notifications to group chats and 500 per month on a free plan is really low to be honest. I believe it should have similar constraints like the multicast or broadcast messages

**Comment by tkgauri** [comment] 2020-03-12 07:25
We are closing this issue now as it is not the issue with the sdk itself.
Thank you for the feedback about push message limit.

**Closed by tkgauri** 2020-03-12 07:25 UTC
