### ISSUE TITLE
richmenu upload image got 415 Unsupported Media Type error

### ISSUE THREAD

**Issue by kaonick** [line/line-bot-sdk-java#259] opened 2018-08-20 08:44 UTC
I have try many  way to upload richmenu image to server , always got the code 415 ?
I need help to solve it.

code is below:
``	
                       
     public String upload(String richMenuId, String exsistingFileName) throws IOException {
		 File file=new File(exsistingFileName);
		 String url = String.format("https://api.line.me/v2/bot/richmenu/%s/content", richMenuId);
		OkHttpClient client = new OkHttpClient();

            RequestBody requestBody=RequestBody.create(MediaType.parse("image/png"), file);
	    RequestBody formBody = new MultipartBody.Builder()
	        .setType(MultipartBody.FORM)
	        .addPart(requestBody)
	        .build();
	    Request request = new Request.Builder().url(url)
	    		.addHeader("Authorization", "Bearer " + BotConfig.LineChannelAccessToken)
	    		.addHeader("Content-Type", "image/png")
	    		.addHeader("Content-Length",""+ file.length())
	    		.post(formBody).build();
	    
	    Response response = client.newCall(request).execute();
	    return response.toString();
	}

**Comment by tokuhirom** [comment] 2019-03-25 11:21
sorry about our too late reply, we can't reproduce it. is it still reproducable?

**Comment by tokuhirom** [comment] 2019-05-22 03:54
we'll close this issue at this time.

**Closed by tokuhirom** 2019-05-22 03:54 UTC
Labels: question
